name: dev-env
services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - ${API_PORT}:${API_PORT}
    env_file:
      - .env
    volumes:
      - ./services/api/demo-api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules

  webapp:
    build:
      context: ./services/webapp
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ./services/webapp/demo-webapp:/usr/src/app
      - webapp_node_modules:/usr/src/app/node_modules

volumes:
  webapp_node_modules: 
  api_node_modules: