name: dev-env
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    volumes:
      - ./api/demo-api:/usr/src/app
      - api_node_modules:/usr/src/app/node_modules

  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./webapp/demo-webapp:/usr/src/app
      - webapp_node_modules:/usr/src/app/node_modules

volumes:
  webapp_node_modules: 
  api_node_modules: