name: dev-env
services:
  # api:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./webapp/demo-webapp:/usr/src/app
      - webapp_node_modules:/usr/src/app/node_modules

volumes:
  webapp_node_modules: